apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-send-to-webhook-slack
spec:
  params:
  - name: webhook-secret
    value: webhook-secret
  - name: message
    value: "This is your Tekton Webhook --- Build Failed!"
  taskRef:
    name: send-to-webhook-slack
